dist: xenial
language: python
python:
- 3.6.9
- '3.7'
install:
- pip install -r requirements.txt
script:
- "/bin/bash -c ci/run.sh"
deploy:
  provider: pypi
  user: __token__
  password:
    secure: uHQipa3+pgdQshRDfOurCPVNKPBZBYpnMPthMhoe2ILYMH92b9FGqoamJru4bOTSrmHAg1CCmRVmq3Rkmv+5AwOXjb/nreY3/JRkwu1CC4iHHVlAqmIVA7LU2de3ub6dutwHrbaO5PoLNZKRrVYZdd10jzCwYUmnOZg5W9lAZ75Lec7HWAMtCfbTnMM5xm5XIxYhTmLSaaBo13WabP4Btamz8PQMP7NTovzYoalHCQeOKK6oKHBoLOE2xu/musuxWGV8TONZJ3QuXsd7+ZH9zTtD34NGci0J2wKDSXkZzUHFhus3UZ4P+OckzEQpOhgkQrVpOm5eNsyw8HQmwjKgilZoGaZuEepVgkugzj/Qg3VphRItWjRXIKbwq+tyGyswQPGiQD3JFmdFYajJWh9zMMp/sUPVqTJl1YTF4296rM9GSA6WekWU7bpnrBXoUex6XIfMzVFaLE1AVc9Qq9M96pz5kp8EraTcWKDrdC8RioPZ11dgy4SYPSyBAWnlzsE4oeynolRUWu3+4z93jPLI12p2SY6l55ji6BwZrXL3oN/2kruhC2IteJSff0spDF5Ou/UtaetZte6LuEPLnPr4/zDi4jCsUz2JVvkclKwehg0h17v8PrWX5U2SsbwhBfmUubph4WVIrrKKsFNr2c83vKCh47S82WgPB1Vg14y1Esk=
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
